spring.security.oauth2.client.registration.google.client-id=498bla-bla
spring.security.oauth2.client.registration.google.client-secret=BLA-BLA

spring.security.oauth2.client.registration.github.client-id=945bla-bla
spring.security.oauth2.client.registration.github.client-secret=GJgr-BLA-BLA
