server.port=9090

spring.profiles.active=multi-jwt

app.jwt.issuer-1=http://localhost:7070
app.jwt.issuer-2=http://localhost:8080

app.jwt.jwk-set-uri=http://localhost:7070/oauth2/jwks

app.opaque.introspection-uri=http://localhost:6060/oauth2/introspect
app.opaque.client-id=resource_server
app.opaque.client-secret=resource_server_secret
